[package]
name = "kintone_record_viewer"
version = "0.1.0"
authors = ["Masataka Miyahara <mstkmyhr@gmail.com>"]

[dependencies]
base64 = "^0.10.0"
prettytable-rs="^0.8.0"
reqwest = "^0.9.0"
serde ="^1.0.80"
serde_derive ="^1.0.80"
serde_json = "^1.0.33"
toml = "^0.4.8"
